name: Publish Docker

on:
   workflow_dispatch:
    
env:
    PROJECT_DOCKERFILE : 'ShippingProAPICollection.RestApi'
    PROJECT_NUNIT : 'ShippingProAPICollection.NUnitTests/ShippingProAPICollection.NUnitTests.csproj'
jobs:

  Build-Publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Login to Docker 
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        file: ./ShippingProAPICollection.RestApi/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/shippproapicollection:latest
