# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Setup Secrets
      run: dotnet user-secrets init --project ShippingProAPICollection.NUnitTests/ShippingProAPICollection.NUnitTests.csproj
    - name: Add Secrets
      run: dotnet user-secrets set "DHLAPIKey" ${{ secrets.DHLAPIKEY }} --project ShippingProAPICollection.NUnitTests/ShippingProAPICollection.NUnitTests.csproj
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
